<?php 
$path = "";

if(isset($_GET['o']))
{ $path = "../"; }
 
?>
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">BALANCE DE TRABAJO DEL PRESIDENTE MUNICIPAL JOSE EDUARDO “CUCO” ROVIROSA RAMIREZ, EN LOS PRIMEROS 15 DIAS DE ACTIVIDADES RUMBO A LAS METAS DE LOS 100 DIAS DE GOBIERNO</h4>
</div>
<div class="modal-body">
    <div class="te">
        <img src="<?php echo($path);?>img/boletin/2_1.jpg" alt="BALANCE DE TRABAJO DEL PRESIDENTE MUNICIPAL JOSE EDUARDO 'CUCO' ROVIROSA RAMIREZ, EN LOS PRIMEROS 15 DIAS DE ACTIVIDADES RUMBO A LAS METAS DE LOS 100 DIAS DE GOBIERNO" class="img-responsive" style="margin: 0 auto;"/><br/>
        <p class="text-justify">Macuspana (16-01-2016).- “Estoy comprometido a que mi gobierno sea de intensa y estrecha comunicación con el pueblo, por lo cual estaré informando puntualmente de todas y cada una de las acciones emprendidas para cambiarle el rostro a Macuspana, para responder a esa confianza y apoyo que he encontrado en la sociedad, la cual se encontraba muy agraviada por la desatención”, manifestó en entrevista el presidente municipal José Eduardo “Cuco” Rovirosa Ramírez.</p>
        <p class="text-justify">Al ajustar las dos primeras semanas de actividades, en las cuales se ha desplegado un intenso trabajo de atención social, el presidente municipal José Eduardo “Cuco” Rovirosa Ramírez hizo un balance de los logros alcanzados, señalando que rumbo a la meta de los “Primeros 100 días de gobierno” se están dando resultados concretos en los rubros de Bacheo en la cabecera municipal y accesos carreteros importantes, así como en el tema del saneamiento del agua potable, la cual llegaba con lodo y bacterias a las tomas domiciliarias.</p>
        <p class="text-justify">Al respecto, el alcalde de Macuspana informó que se ha logrado controlar las decenas de fugas en las tuberías de agua, principalmente en las líneas de alta presión, para lo cual personal de Sapam abrió orificios de gran profundidad en las calles Reforma, Vicente Guerrero, Alatorre, Circunvalación y León Alejo Torres, por donde se escapaba gran cantidad del vital líquido, lo cual impedía el tratamiento del agua con los químicos requeridos.</p>
        <p class="text-justify">En estos momentos, dijo, estoy en la condición de informarles que el agua que está llegando a los hogares está completamente saneada y tratada, por lo cual está libre de gérmenes y bacterias que ponían en riesgo la salud pública.</p>
        <p class="text-justify"> Para ello se adquirieron sustancias químicas para el tratamiento del agua como son los polímeros, gas cloro y una pipa con diez mil litros de sulfato, además de que se lleva a cabo la limpieza integral y desinfección de tanques, filtros y cisterna general. </p>
        <p class="text-justify">Poco a poco se irá aclarando el agua. Además, se solicitó la intervención de la CONAGUA y el CEAS para darle atención al Sistema de Captación sobre el río Puxcatán, porque debido a la falta de mantenimiento durante años se encuentra azolvada y esto provoca que el agua enviada a la planta se encuentra muy sucia, lo cual daña las bombas y provoca interrupciones en el servicio.</p>
        <p class="text-justify">De igual forma, se da atención a los cárcamos ubicados en diferentes puntos de la ciudad, los cuales estaban totalmente azolvados, los cuales se están interviniendo con dos camiones tipo Vactor y se solicitó un tercero al gobierno del estado para avanzar más rápido, al tiempo que se revisan las condiciones de las bombas para dejarlas en condiciones normales de funcionamiento.</p>
        <p class="text-justify">Les comento a los habitantes de las comunidades que también vamos a llegar con la atención a ellos y atender su demanda para que en donde tengan problemas con las bombas o carezcan de ellas se les dé solución y no padezcan la falta del servicio de agua.</p>
        <p class="text-justify">Como presidente municipal le pido mil disculpas a la ciudadanía por las molestias ocasionadas, sólo les pido que me tengan paciencia y me den un voto de confianza, para sacar a Macuspana de tantos baches. La verdad es que hacía falta atacarlos fuertemente, ya que no eran uno ni dos, y lo estamos haciendo a marchas forzadas, con toda energía, para restablecer la vialidad lo más pronto posible y que los automovilistas ya no sufran por el daño a las piezas mecánicas de sus unidades.</p>
        <p class="text-justify">Les comento que estoy muy contento con las empresas y ciudadanos de Macuspana por su solidaridad y respeto con esta cruzada de trabajo emprendida rumbo a los “Primeros 100 días de gobierno municipal”, lo cual me obliga a caminar muy solo, sin escoltas y sin policías, para no quitarle la oportunidad a la gente de platicar libremente y saludar a su presidente. Camino diariamente las calles de Macuspana, visito los mercados públicos y disfruto la rica gastronomía con que cuentan, las cuales les recomiendo ampliamente para venir a disfrutar con sus familias. Quiero ganarme el respeto y la confianza de todos, con trabajo y servicio de calidad, por eso desde las 6 de la mañana me encuentran en la puerta de entrada al Palacio Municipal atendiendo a la ciudadanía que viene de las comunidades y colonias, hablándoles de frente y con la verdad, diciéndoles con franqueza lo que se puede y lo que no se puede hacer. </p>
        <p class="text-justify">Estamos trabajando en Ciudad Pemex, con la rehabilitación y mantenimiento del parque lineal; en Villa Benito Juárez (San Carlos) con bacheo y reparación de los accesos carreteros, desazolve de drenajes y reforzamiento en la recolección de basura.</p>
        <p class="text-justify">Con apoyo de la Junta Estatal y Local de Caminos, de la mano del ingeniero Rubén Cabrales Quiñonez, resolvimos el pésimo estado del tramo carretero de acceso a la cabecera municipal, bajo el puente a desnivel de la carretera federal Villahermosa-Escárcega, frente a la glorieta “Carlos A. Madrazo”, y el correspondiente a la Avenida Tecnológico que da acceso a la colonia Belén.</p>
        <p class="text-justify">Y en lo que corresponde al tramo de 5 kilómetros de la carretera del poblado Aquiles Serdán (San Fernando) a la Y Griega de San Carlos, tenemos informes que sus pobladores concretaron un acuerdo con la empresa Mayakán para proceder a su rehabilitación, pues se encuentra en deplorables condiciones que dificultan el tránsito, y estaremos muy al pendiente de su avance.</p>
        <p class="text-justify">Con respecto al mantenimiento de caminos en las comunidades rurales, que ha sido la demanda constante de los delegados municipales, se están haciendo las gestiones respectivas en coordinación con las autoridades comunitarias para solicitar al gobierno del estado su apoyo, pues cuento con el cariño y solidaridad de los amigos socios de la Unión de Volqueteros de Macuspana para tirar la grava en los caminos dañados una vez que tengamos a la mano los vales que necesitamos.</p>
        <p class="text-justify">Quiero decirles a los amigos de las Uniones de Taxis del municipio y que lo tengan bien presente, que próximamente buscaré entrevistarme con las autoridades federales de la SCT, para gestionar el mejoramiento de las condiciones del tramo carretero que va de la Caseta de Cobro de Dos Montes a Macuspana, porque representa un serio riesgo a la seguridad de los automovilistas y grandes daños para sus unidades.</p>
        <p class="text-justify">El alcalde José Eduardo “Cuco” Rovirosa anunció que a partir del 1 de febrero darán inicio los operativos de tránsito, porque no podemos dejar a la ciudadanía indefensa. Por lo cual invitó a todos los conductores a regularizar sus documentos y vehículos motorizados, a retirar los polarizados, hacer uso del cinturón de seguridad, no hablar por el celular si está conduciendo. El llamado incluye tanto a los propietarios de vehículos como a tricicleros y motociclistas. No vengo a asaltar a nadie, ni vengo a querer resolver los problemas de Macuspana con las multas de los ciudadanos, para eso me pinto solo como gestor, pero no podemos dejar indefensa a la sociedad ante cualquier atropello o accidentes que pueda suscitarse, subrayó.</p>
        <p class="text-justify">En cuanto a las críticas constructivas son bien aceptadas, las atenderemos para mejorar; pero a los golpes mediáticos y sin sustento haremos oídos sordos, porque nadie me va a parar, nadie me va a detener en el objetivo de lograr el progreso para mi pueblo y poner su reloj a tiempo. Que ladren todo lo que quieren, que yo seguiré trabajando arduamente y sin descanso para devolverle la esperanza a Macuspana de tener un mejor futuro.</p>
        <p class="text-justify">Para concluir, el primer regidor del Ayuntamiento de Macuspana, sobre la relación y colaboración con el gobierno del estado, puntualizó que “estoy muy contento con el gobernador Arturo Núñez y con su esposa, la señora Martha Lilia López Aguilera. La presidenta del DIF estatal le ha brindado una excelente atención a mi esposa Crystel, incluso la acompañó en los primeros días de este mes a la entrega de juguetes en la ranchería Bonanza segunda sección; y con el gobernador les puedo  decir que tenemos una relación de lujo. Los presidentes municipales de otro partido ajenos al suyo  le aprendimos que para el licenciado Núñez el  día 7 de junio ya pasó y quedó atrás, lo único que quiere como gobernador es trabajar bien por Macuspana y por el estado, es un hombre con pasión para componer a Tabasco”.</p>
    </div>
</div>
<div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
</div>